### ISSUE TITLE
Another 502 Bad Gateway Problem

### ISSUE THREAD

**Issue by hofstee** [JPHutchins/open-energy-view#39]
Not sure if this should really be a new issue since it seems to be a recurring thing, but as best I can tell things seemed to have been working for others ~a week ago? I can authorize permissions with PG&E but then it gets stuck loading when it returns to the app, and if I check the console and try to look at what's going on there's a GET request receiving a 502.

**Comment by JPHutchins** [comment]
@hofstee It's always a new issue 😄 !

I've found a few problems.

In this snippet, if "interval block url" cannot be retrieved, it wants to return a 500 error to the user.  This won't work though because the function that called this is expecting a task ID not a response.
https://github.com/JPHutchins/open-energy-view/blob/4b083cc700f3c8adb67ff1a720b411bbae768557/open_energy_view/utility_apis.py#L459-L468

Instead of trying to return a 500 to the caller, pasted below, it would be easy to raise an exception that gets handled same is the IntegrityError.  As it is, line 389 results in an exception because it has no idea what to do with the "500 error" returned by the function in the first snippet.
https://github.com/JPHutchins/open-energy-view/blob/4b083cc700f3c8adb67ff1a720b411bbae768557/open_energy_view/resources.py#L374-L397

This will not solve the root cause of the issue.  But maybe it can give a more clear error message that can help to root cause the issue.

**Comment by JPHutchins** [comment]
@hofstee I've pushed the update described above, https://github.com/JPHutchins/open-energy-view/commit/ba09e020e0057d659ff432fef01811f73a6f0a08, so when you have a chance feel free to try again.  Note the time so I can check the logs specific to your attempt.

**Comment by hofstee** [comment]
I've made a few more attempts just now (~4:30 PST) and the first one had a POST to a 502 in the console, and the second attempt doesn't seem to show data nor anything in the console, it just brought me to the dashboard.

**Comment by JPHutchins** [comment]
Hi @hofstee, thank you for testing again!  Yours is one of the lucky accounts (like my own) that provides data in 900 second intervals.  Currently these 900 second intervals are not supported and it it is a top priority for me to fix.  I'll will tag you when your data will actually show up in the frontend.  Follow here: https://github.com/JPHutchins/open-energy-view/issues/30

**Comment by hofstee** [comment]
Thanks for letting me know!
